#! /bin/bash

docker container stop zope-docker || true
docker rm zope-docker || true

# Example for adding a mount
# --mount type=bind,source=<REPLACE ME WITH A REAL PTH>,target=/vol \

docker run \
    -p 8080:8080 \
    -it \
    --name zope-docker \
    klappson/docker-zope-setup
